#
//  ios-ci.yml
//  LocalizationDemo
//
//  Created by Baby Chandana Kamalapuram on 05/06/26.
//

name: iOS CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main







jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Xcode Version
        run: xcodebuild -version

      - name: Build App
        run: |
          xcodebuild \
          -project LocalizationDemo.xcodeproj \
          -scheme LocalizationDemo \
          -destination 'platform=iOS Simulator,name=iPhone 16' \
          build
